-- +goose Up

-- Adds 'set_category' as a third automation_rule_actions action type,
-- targeting a categories row, alongside the existing 'ignore' and
-- 'reconcile' — see 00015_automation_rule_actions.sql's doc comment, which
-- anticipated exactly this. A rule may now carry more than one action (e.g.
-- set_category + reconcile together); application code no longer pins rules
-- to exactly one action. Rebuilt via copy-swap since Postgres CHECK
-- constraints can't be altered in place without depending on
-- autogenerated constraint names, mirroring the sqlite migration exactly.
CREATE TABLE automation_rule_actions_new (
    id                      TEXT PRIMARY KEY,
    rule_id                 TEXT NOT NULL REFERENCES automation_rules (id) ON DELETE CASCADE,
    action_type             TEXT NOT NULL CHECK (action_type IN ('ignore', 'reconcile', 'set_category')),
    recurring_commitment_id TEXT REFERENCES recurring_commitments (id) ON DELETE RESTRICT,
    category_id             TEXT REFERENCES categories (id) ON DELETE RESTRICT,
    position                INTEGER NOT NULL CHECK (position >= 0),
    UNIQUE (rule_id, position),
    CHECK (
        (action_type = 'ignore' AND recurring_commitment_id IS NULL AND category_id IS NULL) OR
        (action_type = 'reconcile' AND recurring_commitment_id IS NOT NULL AND category_id IS NULL) OR
        (action_type = 'set_category' AND category_id IS NOT NULL AND recurring_commitment_id IS NULL)
    )
);
INSERT INTO automation_rule_actions_new (id, rule_id, action_type, recurring_commitment_id, category_id, position)
SELECT id, rule_id, action_type, recurring_commitment_id, NULL, position FROM automation_rule_actions;
DROP TABLE automation_rule_actions;
ALTER TABLE automation_rule_actions_new RENAME TO automation_rule_actions;

CREATE INDEX idx_automation_rule_actions_recurring_commitment_id
    ON automation_rule_actions (recurring_commitment_id);

CREATE INDEX idx_automation_rule_actions_category_id
    ON automation_rule_actions (category_id);

-- At most one reconcile action may target a given commitment at a time —
-- internal/timeline reads "the" reconcile rule for a commitment as a 1:1
-- lookup (see internal/automation.ListActiveReconcileTargets).
CREATE UNIQUE INDEX idx_automation_rule_actions_one_reconcile_per_commitment
    ON automation_rule_actions (recurring_commitment_id)
    WHERE action_type = 'reconcile';

-- +goose Down

CREATE TABLE automation_rule_actions_old (
    id                      TEXT PRIMARY KEY,
    rule_id                 TEXT NOT NULL REFERENCES automation_rules (id) ON DELETE CASCADE,
    action_type             TEXT NOT NULL CHECK (action_type IN ('ignore', 'reconcile')),
    recurring_commitment_id TEXT REFERENCES recurring_commitments (id) ON DELETE RESTRICT,
    position                INTEGER NOT NULL CHECK (position >= 0),
    UNIQUE (rule_id, position),
    CHECK (
        (action_type = 'ignore' AND recurring_commitment_id IS NULL) OR
        (action_type = 'reconcile' AND recurring_commitment_id IS NOT NULL)
    )
);
INSERT INTO automation_rule_actions_old (id, rule_id, action_type, recurring_commitment_id, position)
SELECT id, rule_id, action_type, recurring_commitment_id, position
FROM automation_rule_actions WHERE action_type IN ('ignore', 'reconcile');
DROP TABLE automation_rule_actions;
ALTER TABLE automation_rule_actions_old RENAME TO automation_rule_actions;

CREATE INDEX idx_automation_rule_actions_recurring_commitment_id
    ON automation_rule_actions (recurring_commitment_id);

CREATE UNIQUE INDEX idx_automation_rule_actions_one_reconcile_per_commitment
    ON automation_rule_actions (recurring_commitment_id)
    WHERE action_type = 'reconcile';
