-- +goose Up

-- day_of_month conditions moved from "near_day" (a tolerance around the
-- linked commitment's expected day, injected at resolve time by
-- internal/recurrences) to "day_range" (a plain absolute "<min>:<max>"
-- window, independent of any specific occurrence — see internal/rules).
-- Rebuilt via copy-swap rather than ALTER TABLE ... DROP CONSTRAINT to avoid
-- depending on Postgres's autogenerated constraint names, mirroring
-- 00016_widen_automation_conditions_drop_commitment_conditions.sql. This
-- repo hasn't gone to production, so any existing near_day rows are dropped
-- rather than migrated (there's no automatic way to turn a relative
-- tolerance into an absolute range without knowing the occurrence day).
DELETE FROM automation_rule_conditions WHERE operator = 'near_day';

CREATE TABLE automation_rule_conditions_new (
    id       TEXT PRIMARY KEY,
    rule_id  TEXT NOT NULL REFERENCES automation_rules (id) ON DELETE CASCADE,
    field    TEXT NOT NULL CHECK (field IN ('description', 'card', 'account', 'amount', 'day_of_month')),
    operator TEXT NOT NULL CHECK (operator IN ('contains', 'equals', 'within_percent', 'day_range')),
    value    TEXT NOT NULL CHECK (trim(value) <> ''),
    position INTEGER NOT NULL CHECK (position >= 0),
    UNIQUE (rule_id, position)
);
INSERT INTO automation_rule_conditions_new SELECT * FROM automation_rule_conditions;
DROP TABLE automation_rule_conditions;
ALTER TABLE automation_rule_conditions_new RENAME TO automation_rule_conditions;

-- +goose Down

DELETE FROM automation_rule_conditions WHERE operator = 'day_range';

CREATE TABLE automation_rule_conditions_old (
    id       TEXT PRIMARY KEY,
    rule_id  TEXT NOT NULL REFERENCES automation_rules (id) ON DELETE CASCADE,
    field    TEXT NOT NULL CHECK (field IN ('description', 'card', 'account', 'amount', 'day_of_month')),
    operator TEXT NOT NULL CHECK (operator IN ('contains', 'equals', 'within_percent', 'near_day')),
    value    TEXT NOT NULL CHECK (trim(value) <> ''),
    position INTEGER NOT NULL CHECK (position >= 0),
    UNIQUE (rule_id, position)
);
INSERT INTO automation_rule_conditions_old SELECT * FROM automation_rule_conditions;
DROP TABLE automation_rule_conditions;
ALTER TABLE automation_rule_conditions_old RENAME TO automation_rule_conditions;
